### PR TITLE
Initialize siginfo before use in 't' mode

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
An alternate solution would be to hide the uses of `siginfo_*` in 763fa25 with

    if (mode == 'x')

... actually, the more I think about it, the more I'm leaning towards that solution.

**Comment by gperciva** [comment]
I uploaded the alternate solution to this PR; if you prefer it, I'll twiddle the history accordingly.  Do not merge this branch in the current state.

**Comment by cperciva** [comment]
The revised solution looks good to me.

**Comment by gperciva** [comment]
Revised history, and added extra comments explaining **why** this is only in 'x' mode, because otherwise I'll forget and be tempted to "clean it up".

I debated between `/* Siginfo... */` and `/* siginfo`; going with the latter becaues that's what the function / variable / file is called.  I could capitalize it if the grammar offends you, though.

**Pull request merged**
