### PR TITLE
Libcperciva import event cleanup

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
In spiped, we waited a month and a half between these commits and actually removing `events_shutdown`.  I think the reason was to make it easier to revert changes if necessary.

Do you want to have a similar delay here, or should I remove `events_shutdown()` from `lib/network/tsnetwork_select.c` right now?

**Comment by cperciva** [comment]
Just go ahead and remove `events_shutdown` now.

**Comment by gperciva** [comment]
Done, ready for merge.

**Comment by cperciva** [comment]
Looks like you removed the call to `events_shutdown` but didn't actually remove `events_shutdown`?

**Comment by gperciva** [comment]
Yes, because we haven't removed it from libcperciva (yet).

**Comment by gperciva** [comment]
https://github.com/Tarsnap/libcperciva/blob/master/events/events.c#L245

**Comment by cperciva** [comment]
Oh right, I forgot about that.

**Pull request merged**
