### PR TITLE
Apply --humanize-numbers to SIGINFO output

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Addresses #164 .  One person suggested giving the byte count as well (i.e. "2.1 GB / 3.0 GB (2100123456 / 3000123456)"), but on second thought I'm not convinced that's necessary.  I can add it easily if desired, though.

**Comment by cperciva** [comment]
The code looks good, but shouldn't this be documented somewhere?

**Comment by cperciva** [comment]
Err, whoops.  I didn't see the man page updates at the bottom...

**Comment by cperciva** [comment]
Should probably get a mention in NEWS anyway though, since it's a clearly user-visible change.

**Pull request merged**
