### PR TITLE
build: getfstype.c, memlimit.c requires non-POSIX

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Fixes #181 with `#undef _POSIX_C_SOURCE`.

It seems plausible that getting info about filesystems and memory limits requires non-portable code.

**Comment by cperciva** [comment]
Hmm, "We use" seems like it would be more idiomatic than "We require"?

**Comment by gperciva** [comment]
If we could get the filesystem type with POSIX functions, wouldn't we do that?

Anyway, updated with "We use".

**Comment by cperciva** [comment]
Well, we *should* use only POSIX functions if we can do what we need that way.  But it's best to be clear about what we're saying.

**Pull request merged**
