### PR TITLE
Verify config

### PR DESCRIPTION
**Pull request by gperciva**
Addresses #132.

It's not clear to me from the quoted text that the user really wants to ignore missing keyfiles (unless I'm misunderstanding something about "feather").  And if we really don't want to complain about missing keyfiles, then I'm not certain why @cperciva wanted the `--keyfile` code to be "store the path and load the keys later" since we wouldn't be loading them (?).  But this is a decent starting place for a discussion.

### CODE REVIEW

**Comment by cperciva** [comment]
> It's not clear to me from the quoted text that the user really wants to ignore missing keyfiles

The use case here is "syntax-check a tarsnap configuration file before deploying it to the systems which will use it".  The configuration file won't necessarily be edited on a system with all the same keys in the same places.

**Comment by gperciva** [comment]
From offline discussion, @cperciva wanted this to warn if there's two keyfiles given.  But `dooption()` contains:

```
optset:
        /* Option specified multiple times. */
        if (fromconffile == 0) {
                usage(bsdtar);
        }
        return;
```

so it looks like tarsnap currently deliberately ignores repeated options from config files.

**Comment by cperciva** [comment]
Ok, I remember what it was that I saw earlier.  Yes, we ignore multiple options from configuration files, since that's how overriding keys works.

The issue actually has nothing to do with `--verify-config` except that it touches some of the same code; it's actually a problem with the keyless dry-run code.  If we're doing a dry run and `~/.tarsnaprc` specifies a key file which we can't key, we don't set `have_keys` and then we try to read and use the keyfile specified in `/usr/local/etc/tarsnap.conf`.  Which would (a) result in the warning being skipped (since we would have keys, albeit the wrong ones) and (b) result in bogus statistics (since using the wrong keys would break deduplication).

Can you fix that bug and then come back to this afterwards?

**Comment by gperciva** [comment]
Updated; this PR depends (and includes) #138.

**Comment by gperciva** [comment]
Updated with much simpler "bail early" approach.

**Pull request merged**
