### PR TITLE
Fix uninitialized variable in subst.c

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
This was accepted upstream:
    https://github.com/libarchive/libarchive/pull/790

**Comment by gperciva** [comment]
Shouldn't merge yet: how much of a bug bounty is this worth?

**Comment by cperciva** [comment]
A bug which causes tarsnap to crash is a $100 bounty.

**Comment by gperciva** [comment]
Updated and ready for merging.

**Pull request merged**
