### PR TITLE
Avoid reading uninitialized memory during -x

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by cperciva** [comment]
Correct fix, incorrect commit message.  The problem isn't that a->path_safe is being accessed; it's that a->path_safe was never initialized.  So the fix is "initialize no-nasty-symlinks safe path".  (Remember, valgrind is a tool but not a very smart one.  It correctly identified that there was a bug, but you have to understand the code to figure out what the bug is.)

This would be a security problem except that I'm pretty sure this is allocated too soon for anyone to get anything nasty into a newly allocated buffer.  But please check if libarchive still has this bug, since this is the sort of thing which absolutely needs to be upstreamed.

**Comment by gperciva** [comment]
Patch updated.  I'll check upstream later today.

**Comment by gperciva** [comment]
Wait a bit; I'm not certain this is the right spot to put that fix.  Checking how things are done upstream.

**Comment by gperciva** [comment]
I found a different fix upstream, and figured it would be better to use theirs.
https://github.com/Tarsnap/tarsnap/pull/53

**Pull request closed without merging**
