### PR TITLE
Travis-CI: update to the latest config

### PR DESCRIPTION
**Pull request by gperciva**

### CODE REVIEW

**Comment by gperciva** [comment]
Hmph, it's passed Tavis-CI, but the message is't getting back to github. I'll try again in an hour.
https://travis-ci.org/github/Tarsnap/tarsnap/builds/678267332

**Comment by cperciva** [comment]
Can you poke Travis-CI and/or Github to unwedge this?

**Comment by cperciva** [comment]
(LGTM aside from Github being broken though.)

**Comment by gperciva** [comment]
Looks good now.

**Pull request merged**
